- name: Install binary
  copy:
    src: "{{ artifact_path }}"
    dest: "/etc/updatecli/{{ artifact_name }}"
    mode: '0755'

- name: Create systemd service file
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true


- name: Enable and start the service
  block:

    - name: Enable and restart the service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: true
        state: restarted

  rescue:

    - name: Fetch service logs after failure
      shell: |
        journalctl -u {{ service_name }}.service --no-pager -n 50 || echo "No logs found"
      register: service_logs
      ignore_errors: true

    - name: Display service logs
      debug:
        var: service_logs.stdout_lines

    - name: Fail with context
      fail:
        msg: "Service {{ service_name }} failed to start. See logs above."
