name: Dispatched Build and publish RaspAP images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-base.outputs.cache-hit }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up QEMU and Docker Buildx
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Cached Work Directory
        id: cache-base
        uses: actions/cache@v4
        with:
          path: pi-gen/work
          key: pi-gen-base-v1
          restore-keys: |
            pi-gen-base-

      - name: Build Base Image if Cache is Missing
        if: steps.cache-base.outputs.cache-hit != 'true'
        uses: usimd/pi-gen-action@v1
        with:
          image-name: base-raspios
          stage-list: stage0 stage1 stage2

      - name: Ensure Work Directory Exists
        run: mkdir -p pi-gen/work

      - name: Cache Updated Work Directory
        if: steps.cache-base.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: pi-gen/work
          key: pi-gen-base-v1

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Work Directory
        uses: actions/cache@v4
        with:
          path: pi-gen/work
          key: pi-gen-base-v1
          restore-keys: |
            pi-gen-base-

      - name: Run Pi-gen Custom Build
        uses: usimd/pi-gen-action@v1
        with:
          image-name: custom-raspios
          stage-list: stage3
          # stage-list: stage3 custom-stage
          work-dir: pi-gen/work
          continue: true

      - name: Upload Final Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-raspios-image
          path: pi-gen/deploy/*.zip
          retention-days: 30
