name: Build Image

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build RPi Image
        uses: ./.github/actions/build-rpi-image
        with:
          source_repo: 'jamtools/jamscribe'
          version_prefix: 'vjamscribe-'
          github_token: ${{ secrets.GITHUB_TOKEN }}
