name: Build Image

on: push

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases repo into `.github/composite-actions`
        uses: actions/checkout@v3
        with:
          repository: jamtools/rpi-deploy
          path: .github/composite-actions
          ref: ${{ github.sha }}

      - name: Build RPi Image
        uses: ./.github/composite-actions/.github/actions/build-rpi-image
        with:
          source_repo: 'jamtools/jamscribe'
          version_prefix: 'vjamscribe-'
          github_token: ${{ secrets.GITHUB_TOKEN }}
