name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install modules
              run: npm i
            - name: Build app
              run: npm run build
    types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install modules
              run: npm i
            - name: Check Types
              run: npm run check-types

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'
            - name: Install modules
              run: npm i
            - name: Run tests
              run: npm run test:ci
